### ISSUE TITLE
ValueError : Format 'jpg' is not supported

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#10]
Hello @Cartucho i confuse for this error, it never occur before 
![image](https://user-images.githubusercontent.com/37479922/38777459-b1c80646-40d2-11e8-9b73-db26a1b12488.png)

i run main.py after use convert and change name class, 
can you help me please ?

**Comment by Cartucho** [comment]
It seems to be a problem with `jpg` and matplotlib.
I changed the format to `png`, should work now.

**Comment by andikira** [comment]
i try in my laptop now (it's work), error occur in my pc, sorry i can't try it now, i'll try it tomorrow.
Thank you so much

**Comment by andikira** [comment]
It's work now, thank you
