### ISSUE TITLE
Weird way to calculate recall

### ISSUE THREAD

**Issue by PaulZhangIsing** [Cartucho/mAP#101]
In line 667-668
'''
 for idx, val in enumerate(tp):
            rec[idx] = float(tp[idx]) / gt_counter_per_class[class_name]
'''
It looks that the recall is calculated based on number of total number of objects in the samples, rather than the number of the objects in the particular image.....

Based on my understanding, I suspect there is something wrong in this code??

**Comment by Cartucho** [comment]
Why? You do not calculate recall for a particular image but rather for a class of objects.

This code is based on the official Matlab code of the PASCAL VOC challenge. Please have a look there, you can download the matlab code and have a look (:

**Comment by PaulZhangIsing** [comment]
> Why? You do not calculate recall for a particular image but rather for a class of objects.
> 
> This code is based on the official Matlab code of the PASCAL VOC challenge. Please have a look there, you can download the matlab code and have a look (:

Thanks I understand. I misundetstood it as the recall and precision for each image.
