### ISSUE TITLE
False Negative

### ISSUE THREAD

**Issue by nemeziz69** [Cartucho/mAP#102]
How do I calculate the false negative?

**Comment by Cartucho** [comment]
Qualitatively you can see the false negatives, drawn in pink

**Comment by pauloamed** [comment]
This for loop creates pink bounding boxes for each unmatched ground-truth bounding box.
```
        for obj in ground_truth_data:
            if not obj['used']:
                bbgt = [ int(round(float(x))) for x in obj["bbox"].split() ]
                cv2.rectangle(img,(bbgt[0],bbgt[1]),(bbgt[2],bbgt[3]),pink,2)
```

@Cartucho Your work is awesome! Congratulations

**Comment by anjanaouseph** [comment]
> Qualitatively you can see the false negatives, drawn in pink

Hi, but in the final graph of Average precision, there is no FN, its only TP and FP.
