### ISSUE TITLE
mAP is coming out to be 0.00

### ISSUE THREAD

**Issue by rohanbanerjee** [Cartucho/mAP#123]
Hi @Cartucho 
Thank you for the amazing script
I am having an issue while calculating the mAP for my class. In my case, I just have a single class to be detected and I have performed all the mentioned steps exactly in the proper sequence.

I observed that all the bounding boxes that are present in the txt files are not being drawn on the images. 
I am not exactly able to understand the problem here but I am getting an mAP of 0.00 even though I can clearly see that the model is very confident in detecting the objects.

Any insight on this would be really helpful
Thanks!

**Comment by saurabbhsp** [comment]
I had the same issue. I changed the format to (xmin ymin xmax ymax)
