### ISSUE TITLE
TypeError : unorderable type : str() > int ()

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#13]
Hello @Cartucho, there is error in your new feature (always from me 😆 ).
![image](https://user-images.githubusercontent.com/37479922/38970643-d90f4d7c-43c0-11e8-95b8-17db2ec123ea.png)

i think this error occur because i have 0 prediction for "eosinofil" (0% AP). This error make your new graph not generate in the result folder.  
Thank you, as usual this is will be easy for you. 😆

**Comment by Cartucho** [comment]
Ups! My mistake!

Can you please try it now?

**Comment by andikira** [comment]
Great, work perfectly now.
