### ISSUE TITLE
Is the confidence only used for sorting?

### ISSUE THREAD

**Issue by SingL3** [Cartucho/mAP#133]
Hi, I read the evaluation code of wider face dataset and compare it with this repo.
As I can see, the confidence is only used for sorting the detection result in this repo.
In the evaluation code of wider face, seem it used confidence to decide to calculate the pr info.
I have tested to let my confidence become "new_confidence = 0.1 x confidence + 0.6" to keep the order but different from the real confindence. And I got similar mAP.
So is this an error or did I misunderstand the mAP?

**Comment by mfiro** [comment]
Good point! Can you please send the a link to the "evaluation code of wider face"?

**Comment by SingL3** [comment]
@mfiro 
http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/support/eval_script/eval_tools.zip
or
http://shuoyang1213.me/WIDERFACE/support/eval_script/eval_tools.zip

**Comment by eunyoung1124** [comment]
I also wonder 'confidence' is not necessary for calculating mAP? It seem to used only showing on image.

**Comment by SingL3** [comment]
I think the code of wider face is correct.
The only different is that you should read all the detection results with confidence and normalize them using (confidence - min) / (max - min). This also helps one to choose the best score theshold for deployment.(For a two-class classifier, it is not always the best to choose 0.5 as threshold)
This is my understanding. Feel free to share yours.
