### ISSUE TITLE
Animation and Row Order of Objects

### ISSUE THREAD

**Issue by lobbie** [Cartucho/mAP#14]
Hi,

Just wondering if it is true that the animation will show the boundary boxes of predictions, or where gt and predictions overlapped? I.e. ground truth boxes without predictions overlapping will not be shown?

Does the row order of objects in the prediction files matter?  Example for Image A, the ground truth has 3 cars and the row order of the cars in the ground truth file is sorted by xmin in ascending order.  However, the prediction is ordered by car 2, car 1 and then car 3.

cheers,
Lobbie

**Comment by Cartucho** [comment]
> Just wondering if it is true that the animation will show the boundary boxes of predictions, or where gt and predictions overlapped? I.e. ground truth boxes without predictions overlapping will not be shown?

The animation is currently showing the predictions (in green or red) and correspondent ground-truth (in blue) if exists. When you calculate the AP you iterate through the ranked predictions, that is why "in practice" some ground-truth instances will not be used.

![image](https://user-images.githubusercontent.com/15831541/39083237-8d7c505e-4559-11e8-8cb7-d269e1c660ca.png)

Do you think it would be useful to also show in the animation the ground-truth instances that were not used?
I think a great feature would be for the people to be able to see the animation, step by step while calculating the AP for each class. e.g. it would plot and show the respective image at each time. This would help people understand what is going on. 

> Does the row order of objects in the prediction files matter? Example for Image A, the ground truth has 3 cars and the row order of the cars in the ground truth file is sorted by xmin in ascending order. However, the prediction is ordered by car 2, car 1 and then car 3.

The predictions will be automatically sorted by their confidence. So you do not need to worry about it. Actually, if you check the images in `results/images` you should be able to see it for yourself :grinning: 
Btw, you also gave me another idea. Adding to the images the ranking information of each prediction.

**Comment by lobbie** [comment]
great stuff, mate!  thanks.  I assume I will have to download main.py again to include this feature.  also am wondering what happens to the calculation if gt got bbox while prediction does not and vice versa.  these boxes will not overlap and how does your program takes care of them in the mAP calc?

**Comment by lobbie** [comment]
great stuff, mate!  thanks.
