### ISSUE TITLE
All class P-R curve

### ISSUE THREAD

**Issue by candyotter** [Cartucho/mAP#142]
Is there a way to have the P-R curve for all classes together and not just each individual class?

Thank you

**Comment by AiXinYa** [comment]
> o have the P-R curve for all classes together and not just each individual class?
> 
> Thank you
Reference "Downscaled Faster-RCNN Framework for Signal Detection and Time-Frequency Localization in Wideband RF Systems", You can calculate TP and FP, label the background as 0 and the others (the class in your dataset) as 1, and then calculate the call function VOC_AP to draw the PR cruve.
