### ISSUE TITLE
Fail to show bounding box in multiple object

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#15]
Hello @Cartucho i want to ask you something about image result.
i got a different bounding box picture between mAP result folder and my actual prediction, like this 
![sa_w_51_50](https://user-images.githubusercontent.com/37479922/39087803-94981072-45d0-11e8-8acf-31b48d81a3b4.png)
actual prediction 
![basofil_prediction17](https://user-images.githubusercontent.com/37479922/39087835-12919836-45d1-11e8-8991-34c91ee5000c.jpg)
image from mAP result folder 

this happen when there is a multiple object in one image. 
do you know why ? 
thank you sir

**Comment by Cartucho** [comment]
Hey, are you sure you have that Basofil in the ground-truth?

**Comment by andikira** [comment]
actually there is no basofil (false negative), it think i have misconception about result image. 
does the image (in result folder) show all ground-truth and prediction box ? if yes there is must be show some bounding box in "neutrofil" object

**Comment by Cartucho** [comment]
It goes through each prediction and checks if there is a matching ground-truth with the same class name.
If there is no ground-truth it won't show

**Comment by Cartucho** [comment]
I don't understand the question yet :smile: but yeah sure!

**Comment by andikira** [comment]
i understand now, sorry my bad, one image for one prediction, 
i'm sorry

**Comment by Cartucho** [comment]
@andikira no problem! Any idea on how I could make it more intuitive?

**Comment by andikira** [comment]
i think it's fine
