### ISSUE TITLE
Does the order make an effect？

### ISSUE THREAD

**Issue by curryJ** [Cartucho/mAP#161]
Thank you for your code.
I use this code calculate mAP,but it is 0;My detection-results format and gt-results format are as below
![image](https://user-images.githubusercontent.com/23001027/141684802-7cc4bf5a-3cff-4d50-85ac-3321a37d0631.png)
![image](https://user-images.githubusercontent.com/23001027/141684813-73bbf691-2c75-410f-8421-a6a6a57c601c.png)
so I want to ask that does the order make an effect？I mean the objects' order must be same.

**Comment by curryJ** [comment]
> Thank you for your code. I use this code calculate mAP,but it is 0;My detection-results format and gt-results format are as below ![image](https://user-images.githubusercontent.com/23001027/141684802-7cc4bf5a-3cff-4d50-85ac-3321a37d0631.png) ![image](https://user-images.githubusercontent.com/23001027/141684813-73bbf691-2c75-410f-8421-a6a6a57c601c.png) so I want to ask that does the order make an effect？I mean the objects' order must be same.

I have adderssed this issue;The reason is that my image's size is not equal.

**Comment by IamExperimenting** [comment]
@curryJ , does order really matters here? because I worked out, both the groundtruth and detection should be in the same order.
I also played by shuffling the order, I can see the difference in the mAP.

did you notice the same?

**Comment by curryJ** [comment]
> 

I think the order does not matter.I shuffle the orders in groundtruth and detection results,and I get the same result.Besides,I sort the order and calculate again,the resule is same too.

**Comment by IamExperimenting** [comment]
@curryJ , order which I referred is, bbox coordinates, label, conf score, inside the text file in the ground truth and detection results.

Because, when I shuffled the order of label, bbox, conf score. I can notice the difference in the mAP value.
