### ISSUE TITLE
Possibility to have class specific overlap threshold

### ISSUE THREAD

**Issue by LucasVandroux** [Cartucho/mAP#2]
At first glance, your repo looks nice. You have lots of illustrations to explain the interpolated average precision which is really nice. However, is it possible to have a different threshold for different classes? For example, on the [KITTI benchmark](http://www.cvlibs.net/datasets/kitti/eval_object.php), the cars require an IoU over 70% to be considered as a correct detection while the pedestrians require 50%.

**Comment by Cartucho** [comment]
I will add this feature on Monday.

We can have a dedicated flag for this, either something like:
` --specific-class-iou car 0.7 `
or
` --kitti ` 

I think the first option would be better.

**Comment by Cartucho** [comment]
@LucasVandroux That feature was added to the code, flag usage:

`--set-class-iou [class_1] [IoU_1] [class_2] [IoU_2] [...]`

For example, in your case you have to run:

`python main.py --set-class-iou car 0.7`

By default, all the other classes are set to 0.5 (50%)

**Comment by LucasVandroux** [comment]
@Cartucho, looks nice thanks. I will try it later. It is really a must have 👍
