### ISSUE TITLE
Can I modify the confidence

### ISSUE THREAD

**Issue by someonelikeypp** [Cartucho/mAP#26]
"class_name, confidence, left, top, right, bottom"

can I remove the confidence or set it 0.5 to create the predicted objects files?
because my code couldn't generate confidence after running.
Is it influences result a lot?

thanks for help.

**Comment by someonelikeypp** [comment]
<class_name> <confidence> <left> <top> <right> <bottom>

**Comment by someonelikeypp** [comment]
from here " <class_name> <confidence> <left> <top> <right> <bottom> "

**Comment by Cartucho** [comment]
@someonelikeypp Hello, you mean removing the `confidence` score?
No, you can't do that. The mAP is a **ranked metric** and it ranks the predictions using the `confidence` score, so without it, the result will be meaningless.

**Comment by someonelikeypp** [comment]
ok, i see
thanks
