### ISSUE TITLE
KITTI mAP higher than what this code gives

### ISSUE THREAD

**Issue by aditya1709** [Cartucho/mAP#28]
As far as I know this code is based on the PASCAL VOC definition of mAP. When I use the KITTI's evaluation tool I consistently get a higher mAP as opposed to using this one. Is the any difference between them? 
Any help is appreciated. Thank you for the code.

**Comment by aditya1709** [comment]
Sorry, I figured it out.
KITTI - Detections in don't care areas or detections which are smaller than the minimum size do not count as false positive.
Which is not the case here. Thanks for the code. 
Rule of thumb: If its not an autonomous driving application, use this amazing code. Thanks.

**Comment by Cartucho** [comment]
@aditya1709 Hello! 
Another difference is that the minimum IoU (Intersection over Union) in the KITTI is not 50% for all the classes. I think they use 70% for the person class, but I'm not sure!

Anyway if you want to change the IoU it is possible via one of the flags in the code.
