### ISSUE TITLE
YOLOv3 mAP

### ISSUE THREAD

**Issue by EscVM** [Cartucho/mAP#32]
Hi, I was trying to use your code with [YOLOv3](https://pjreddie.com/darknet/yolo/), but I have some problems to make predictions txt files.
With `./darknet detector test cfg/voc.data yolo-voc.cfg yolo-voc.weights -dont_show -ext_output < data/train.txt > result.txt` I can generate a unique txt file with all results, but I really don't have idea how to parse it.
This is an example of result.txt file:
<Total BFLOPS 65.864 

 seen 64 
Enter Image Path: data/horses.jpg: Predicted in 42.076185 seconds.
horse: 88%	(left_x:    3   top_y:  185   width:  150   height:  167)
horse: 99%	(left_x:    5   top_y:  198   width:  307   height:  214)
horse: 96%	(left_x:  236   top_y:  180   width:  215   height:  169)
horse: 99%	(left_x:  440   top_y:  209   width:  156   height:  142)
Enter Image Path: data/person.jpg: Predicted in 41.767213 seconds.
dog: 99%	(left_x:   58   top_y:  262   width:  147   height:   89)
person: 100%	(left_x:  190   top_y:   95   width:   86   height:  284)
horse: 100%	(left_x:  394   top_y:  137   width:  215   height:  206)
Enter Image Path: >

Thank you so much for your help.

**Comment by pratikbhave2** [comment]
Hey, you can look at my repo:

https://github.com/pratikbhave2/darknet

**Comment by EscVM** [comment]
I don't get it. What is in your repo?

**Comment by pratikbhave2** [comment]
I have Modified Yolo to run detector test on multiple images and save each image with bounding boxes, as well as co-ordinates of the bounding box in a text file(separate text file). You can run it with the same command
.
./darknet detector test cfg/voc.data yolo-voc.cfg yolo-voc.weights -dont_show -ext_output < data/train.txt > result.txt

**Comment by Cartucho** [comment]
Hello!

@EscVM I could help you parse that. Do you think you could send me the full file `result.txt` to here to.cartucho@gmail.com ?

Another option, as mentioned by @pratikbhave2, is to modify the files to save the predictions into separate files.

**Comment by EscVM** [comment]
Thank you @pratikbhave2 and @Cartucho. I'll try both solutions.

**Comment by Cartucho** [comment]
Done! Have a look [here](https://github.com/Cartucho/mAP/tree/master/extra#convert-yolo-to-our-format-1).

Basically, all you have to do is add the `result.txt` to the folder `extra/` and run the command `python convert_pred_yolo.py`

**Comment by Cartucho** [comment]
Btw I did the [python script](https://github.com/Cartucho/mAP/blob/master/extra/convert_pred_yolo.py) with a lot of comments so everything should be easy to understand!

**Comment by EscVM** [comment]
Thank so much @Cartucho ! I really need to improve my Python skills :face_with_head_bandage:

**Comment by buzdarbalooch** [comment]
@Cartucho thanks alot for posts. just a question this is how my result.txt file looks like. 
![image](https://user-images.githubusercontent.com/19202445/48972516-cf76ef80-f023-11e8-83c0-b2aca9364003.png)

when i execute the script (python convert_pred_yolo.py) , i get this error below

![image](https://user-images.githubusercontent.com/19202445/48972542-65127f00-f024-11e8-91db-22aeafb6d64e.png)

**Comment by Cartucho** [comment]
@buzdarbalooch Hello!
Do you think you could send me a sample of the files? So that I can reproduce the error?

to.cartucho@gmail.com

**Comment by creabob** [comment]
> Done! Have a look [here](https://github.com/Cartucho/mAP/tree/master/extra#convert-yolo-to-our-format-1).
> 
> Basically, all you have to do is add the `result.txt` to the folder `extra/` and run the command `python convert_pred_yolo.py`

so how to get result.txt in faster rcnn

**Comment by cyrus303** [comment]
> 
> 
> Hey, you can look at my repo:
> 
> https://github.com/pratikbhave2/darknet

Hey when i run using your repo in yolov3 i am getting segmentation error.. could you help me out please?

/bin/bash: line 1:  1655 Segmentation fault      (core dumped) ./darknet detector test data/obj.data cfg/yolov3_custom_test.cfg /mydrive/weapon_dataset/backup/yolov3_custom_train_last.weights -dont_show -save_labels < data/train.txt > result.txt

**Comment by cyrus303** [comment]
> 
> 
> Done! Have a look [here](https://github.com/Cartucho/mAP/tree/master/extra#convert-yolo-to-our-format-1).
> 
> Basically, all you have to do is add the `result.txt` to the folder `extra/` and run the command `python convert_pred_yolo.py`

Hey, i am not able to find the page. could you redirect me please so that i can find the file

**Comment by Temweka** [comment]
> > Hey, you can look at my repo:
> > https://github.com/pratikbhave2/darknet
> 
> Hey when i run using your repo in yolov3 i am getting segmentation error.. could you help me out please?
> 
> /bin/bash: line 1: 1655 Segmentation fault (core dumped) ./darknet detector test data/obj.data cfg/yolov3_custom_test.cfg /mydrive/weapon_dataset/backup/yolov3_custom_train_last.weights -dont_show -save_labels < data/train.txt > result.txt

I get the same error

**Comment by vadimen** [comment]
here is a simple code, works for yolov3 of v4 or any other, adjust the paths, time or even the command for yourself
```
import os
import subprocess
import time

image_paths_file = '/home/darknet/vadim_configs/test.txt'
path_to_save_images = '/home/darknet/results/'

im_paths = open(image_paths_file, "r").readlines()

obj_dat = "/home/darknet/vadim_configs/obj.data"
yolo_cnf = "/home/darknet/vadim_configs/yolov4-custom.cfg"
yolo_wghts = "/home/darknet/backup/yolov4-custom_best.weights"

for im in im_paths:
    cmd = "./darknet detector test {} {} {} -dont_show \"{}\"".format(obj_dat, yolo_cnf, yolo_wghts, im)

    # The os.setsid() is passed in the argument preexec_fn so
    # it's run after the fork() and before  exec() to run the shell.

    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, preexec_fn=os.setsid)

    # it must be adjuste to your inference speed
    # on my rtx2080 takes 6 seconds max
    time.sleep(6)
    # Send the signal to all the process groups
    #os.killpg(os.getpgid(p.pid), signal.SIGTERM)

    image_name = (im.split('/')[-1]).split('.')[0]
    os.rename("predictions.jpg", os.path.join(path_to_save_images, image_name+'.jpg'))
    print("img was saved")
```

**Comment by tianlanlanlan** [comment]
i changed the code from vadimen a little bit, it no need for wait 6s every time, parent process continue after child process exit
and i copy the ground truth to prediction dir too as a comparison
it worked for me
```
import os
from os import getcwd
import subprocess
import time
import shutil

wd = getcwd()

image_paths_file = "data/train-second/test.txt"
obj_dat = "data/train-second/obj.data"
yolo_cnf = "cfg/yolov4-custom-3.cfg"
yolo_wghts = "backup/yolov4-custom-3_best.weights"
path_to_ground_truth = "data/pic_with_box"

im_paths = open(image_paths_file).read().strip().split('\n')
cfgfilename = yolo_cnf.split('/')[1].split('.')[0]
print(cfgfilename)
path_to_save_predictions = "predictions-%s/"%(cfgfilename)

if not os.path.exists(path_to_save_predictions):
    os.makedirs(path_to_save_predictions)

for im in im_paths:
    if len(im) == 0:
        continue
    cmd = "./darknet detector test %s %s %s -dont_show %s"%(obj_dat, yolo_cnf, yolo_wghts, im)
    print('cmd = %s'%(cmd))
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, preexec_fn=os.setsid)
    # wait max 6s
    p.wait(6)
    # make sure child process exit normally
    if p.poll() != 0:
        print("picture %s predict fails\n"%(im))
        break
    image_name = (im.split('/')[-1]).split('.')[0]
    os.rename("predictions.jpg", os.path.join(path_to_save_predictions, image_name+'.jpg'))
    # cp groud truth near the predictions dir
    # already draw box and saved in path_to_ground_truth dir, if not want to copy, just comment the next line
    shutil.copy(path_to_ground_truth+'/'+image_name+'.jpg', path_to_save_predictions+'/'+image_name+"-truth.jpg")
    print(image_name)

```
![Screenshot from 2022-04-14 23-14-31](https://user-images.githubusercontent.com/34850218/163420680-0cb3fd29-c0e5-4190-8cec-b94957024a6d.png)

**Comment by DikshitV** [comment]
> here is a simple code, works for yolov3 of v4 or any other, adjust the paths, time or even the command for yourself
> 
> ```
> import os
> import subprocess
> import time
> 
> image_paths_file = '/home/darknet/vadim_configs/test.txt'
> path_to_save_images = '/home/darknet/results/'
> 
> im_paths = open(image_paths_file, "r").readlines()
> 
> obj_dat = "/home/darknet/vadim_configs/obj.data"
> yolo_cnf = "/home/darknet/vadim_configs/yolov4-custom.cfg"
> yolo_wghts = "/home/darknet/backup/yolov4-custom_best.weights"
> 
> for im in im_paths:
>     cmd = "./darknet detector test {} {} {} -dont_show \"{}\"".format(obj_dat, yolo_cnf, yolo_wghts, im)
> 
>     # The os.setsid() is passed in the argument preexec_fn so
>     # it's run after the fork() and before  exec() to run the shell.
> 
>     p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, preexec_fn=os.setsid)
> 
>     # it must be adjuste to your inference speed
>     # on my rtx2080 takes 6 seconds max
>     time.sleep(6)
>     # Send the signal to all the process groups
>     #os.killpg(os.getpgid(p.pid), signal.SIGTERM)
> 
>     image_name = (im.split('/')[-1]).split('.')[0]
>     os.rename("predictions.jpg", os.path.join(path_to_save_images, image_name+'.jpg'))
>     print("img was saved")
> ```

Thanks for the code. It works well. How to get output of bounding box coordinates for each image in this file itself?
I'm trying but not possible. Request to assist me.
