### ISSUE TITLE
Errror while running main.py

### ISSUE THREAD

**Issue by giridhar13** [Cartucho/mAP#38]
I get the follwoing error:
(tensorflow1) C:\Users\gvadakku\Downloads\mAP-master>python main.py
Traceback (most recent call last):
  File "main.py", line 555, in <module>
    bbgt = [ int(x) for x in gt_match["bbox"].split() ]
  File "main.py", line 555, in <listcomp>
    bbgt = [ int(x) for x in gt_match["bbox"].split() ]
ValueError: invalid literal for int() with base 10: '407.0'

Is it some kind of bug or the issue is with my data

**Comment by Cartucho** [comment]
Hum... it looks like you have a float where you should have an int.
Do you have at the bounding box location as floats?

**Comment by Cartucho** [comment]
Cool! I have fixed the code, could you please check if this new version is working? So that it won't happen again.
