### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#4]
Hello @Cartucho i've tried your repo, when i run main.py without any change in your repo (ground truth, images, and predicted folder) i got some error says 

Traceback (most recent call last):
  File "main.py", line 178, in <module>
    file_id = file_id.split("/",1)[1]
IndexError: list index out of range

i'm using 
windows 10
python 3.6.4 using anaconda 3
opencv 3.4.1
matplotlib 2.2.2

thanks in advance

**Comment by Cartucho** [comment]
Right, it makes sense since in Windows the dashes are like this `\` instead of like this `/`.
I will fix this!

**Comment by andikira** [comment]
thank for your response sir, do you mean this repo just run on linux ?

**Comment by Cartucho** [comment]
@andikira I just fixed this issue, could you give it a try?
I will now work on the xml

**Comment by andikira** [comment]
its working, thank you so much sir, 
can we have a file picture showing annotation bounding box and prediction box inside it ?

**Comment by Cartucho** [comment]
Cool! I will close this issue then.

Could you please create a new issue asking for those images? And give some ideas on how you would like to have it.
