### ISSUE TITLE
R_P curve graph

### ISSUE THREAD

**Issue by niuniu111** [Cartucho/mAP#49]
When I run the main.py, there are not R_P curve graph, do need it plot by coding myself?

**Comment by xjsxujingsong** [comment]
@niuniu111  in the "results" folder.

**Comment by Cartucho** [comment]
Also, make sure that you installed `matplotlib`:


    python -mpip install -U pip
    python -mpip install -U matplotlib

**Comment by manojsingla0906** [comment]
hi there.. can u help me with SRCNN project. I saw ur comment there that u too didn't find result images. did u find them now, where r they being stored after training and testing is done.. plz help.

**Comment by Cartucho** [comment]
@manojsingla0906 Hello, sorry for the late response, however I did not understand your question

> where r they being stored after training and testing is done

I guess you need to find that information on the README of the github repo that you are using for training your object detector
