### ISSUE TITLE
NameError : name 'xrange' is not defined 

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#5]
I have new issue with this repo, but i am little confuse with this problem
When i run main.py all the function run well, i got mAP score, class AP curve, and number of object per class diagram but i got error says : 

Traceback (most recent call last):
  File "main.py", line 476, in <module>
     plt.xticks(xrange(n_classes), rotation='vertical')
NameError : name 'xrange' is not defined 

maybe i miss some diagram like mAP diagram showing average precision for each class

i use 
windows 10
python 3.5.2
matplotlib 2.2.2

**Comment by Cartucho** [comment]
ok, I think the reason is that `xrange` was renamed in `range` from python 2  to python 3.
I'm fixing it now.

**Comment by Cartucho** [comment]
This should now be solved! Could you please give it a try?

**Comment by andikira** [comment]
Great, there is no error anymore. Now i can see the windows pop up showing the mAP diagram. 
Thank you
