### ISSUE TITLE
prjeddie/darknet Results Format

### ISSUE THREAD

**Issue by Stoltec** [Cartucho/mAP#56]
The prjeddie Darknet implementation [https://github.com/pjreddie/darknet](url) produces separate result files for each class in the result folder. I'm just wondering how I can consolidate them to work with your implementation?

In your _extras_ README it mentioned running Darknet with _darknet.exe_ and I know that the prjeddie version doesn't support Windows so which implementation are you expecting the output from? I could probably work on hunting down the answer myself if I could get that.

**Comment by Stoltec** [comment]
Alright so that seems to be correct and it is the [AlexeyAB fork ](https://github.com/AlexeyAB/darknet)that is expected but `python convert_pred_yolo.py` doesn't appear to function on `results.txt`

**Comment by Stoltec** [comment]
Alright so it turns out with AlexeyAB's fork, redirecting the output to a file can have a hiccup and you simply need to find the resulting line that is missing elements and delete it, or re-run your classifier.

**Comment by Cartucho** [comment]
@Stoltec Hello! Sorry for the super late response! I have been busy.

I am currently working on releasing a new version of this repo that supports all those formats, including  https://github.com/pjreddie/darknet

**Comment by subhasish-ghosh** [comment]
Any updates regarding this issue.
