### ISSUE TITLE
sort FP and TP images in results.

### ISSUE THREAD

**Issue by VinayakaPrabhu** [Cartucho/mAP#57]
Hi @Cartucho 

Thank you for the extremely helpful repo.

Is there any way to sort False Positive and true positive images in the results ?
This will be helpful.

Thank you.

**Comment by Cartucho** [comment]
Hello, yes sos the green ones are the TP and the red ones are the FP.

I am planning on adding also the orange ones which will correspond to the false negatives.

**Comment by attanzion** [comment]
> Hello, yes sos the green ones are the TP and the red ones are the FP.
> 
> I am planning on adding also the orange ones which will correspond to the false negatives.

I need True negative too, how can i have them? I added false negatives but I don't know how to add the true negatives.

**Comment by PavanproJack** [comment]
HI, @attanzion  I couldn't get false negatives. I think there something wrong with the placement of False negatives script in main.py. 
Could you please help me on how to get the number displayed?

Regards
Pavan K
