### ISSUE TITLE
TypeError : integer argument expected, got float

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#6]
Hello @Cartucho , this repo improvement is so great. 
I got some error in this update, like this
![image](https://user-images.githubusercontent.com/37479922/38171208-1995c156-35bf-11e8-9228-df539be0c62d.png)

Maybe this is because i have no predict any "Platelets", when i have 3 classes (RBC, WBC, platelets)
I hope you can solve this, thank you.

**Comment by Cartucho** [comment]
I think it is fixed now. :+1:

**Comment by andikira** [comment]
yeah it's working now, thank you
