### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by VinayakaPrabhu** [Cartucho/mAP#61]
Hello @Cartucho 
Thank you for all your support. This repo is extremely helpful.

I have few questions. Could you please help me.
I have 1 class and predicted using tinyYolo
Q1 ) How should we know which threshold is best to choose?
at 0.1 Threshold I got mAP : 63.07% , lamr : 0.52 , FP : 3942 and TP 1460.
at 0.3 Threshold mAP : 59.72% , lamr : 0.52 , FP : 861 and TP 1325.
at 0.5 Threshold mAP : 52.24% , lamr : 0.57 , FP : 861 and TP 1121

So. Is there a way to find an optimal threshold at one go?

Q2.) What is the difference between lamr and ROC? (I am not clear with both terms)

Q3 ) Is there any difference between IOUThreshold and threshold?If so could you please explain.

Sorry. If the question look dumb or illogical. I am new to the topic

Thank you for your time.

**Comment by Cartucho** [comment]
Hello @VinayakaPrabhu ! I am so sorry for the late response. Do you still have these questions?

**Comment by VinayakaPrabhu** [comment]
@Cartucho . Thank you for the reply.

Yeah. I got the answers.
