### ISSUE TITLE
directory "images" naming inconsistencies 

### ISSUE THREAD

**Issue by chrmertz** [Cartucho/mAP#69]
Hello,

thanks for your great work, great help for me. 
There is an inconsistency between the instructions (README.md) and the code. In the README.md you say:

Optional (if you want to see the animation):

    Insert the images into the folder input/images/

But in the code and in the repository you use "input/images-optional"

**Comment by Cartucho** [comment]
Hello, thank you so much for pointing this out! I have just [fixed it](https://github.com/Cartucho/mAP/commit/20d2f89d90a1b5ca119871e925132af32ab61b74).
