### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by f4br1** [Cartucho/mAP#7]
Hi,

I have my ground truth in Pascal VOC formal which I'm planning to extract the coordinates of the objects my images contain. Pascal VOC xml files have coordinates as:
xmin: 235
ymin: 100
xmax: 324
ymax: 171

what is the proper order to use for your implementation since you your format is:
left, top,right,bottom?

Thanks!

**Comment by Cartucho** [comment]
Hello,

So both your ground-truth and predicted object files are in the `.xml` format?

If you prefer you can send me some files as an example: to.cartucho@gmail.com

**Comment by f4br1** [comment]
I have ground truth  in `.xml` for each image and the predicted values are in the form:
[`class`    `conf`  `xmin`   ` ymin`    `xmax`    `ymax`]

My algorithm is designed to detect just a single class, `cat` for example. There are no other classes to detect.

Does you mAP is valid for this case?

Thanks!

**Comment by Cartucho** [comment]
yes, it is still valid, mAP will be the same as the AP for that class.

In the extra `folder` you can find some code to convert the `.xml` to `.txt`.
Let me know if it worked.

**Comment by Cartucho** [comment]
did it work?

**Comment by f4br1** [comment]
Hi, yes I made some minor changes to adapt the code for my task, but overall is working fine. Thanks.

**Comment by Cartucho** [comment]
ok, cool! Did you try that code? the one that converts `xml` to `txt`?

Just to know if I can close the issue

**Comment by f4br1** [comment]
Yes, I tried it. You can close it now. Thanks again !

**Comment by bitwangdan** [comment]
@f4br1 hi, my data format is same to you(xmin, ymin, xmax, ymax), but the author's data format is <left, top , right, bottom>, Are these two in the same order?

**Comment by f4br1** [comment]
Hi,

Yes, the order is the same.

Best,
F4br1
