### ISSUE TITLE
AP is calculated as 0 despite exact bbox match

### ISSUE THREAD

**Issue by micah5** [Cartucho/mAP#70]
I'm having a problem where even if I copy my detection results directly from the ground truth (adding a confidence score of 1.0), certain bounding boxes give an AP of 0 and bring down the mAP unnecessarily.

For example, try adding `1.txt` to `detection-results` containing:
`dog 1.0 206 394 173 405`
and `1.txt` to `ground-truth` containing:
`dog 206 394 173 405`

You'll see that it'll return a mAP of zero, despite the bboxes being exactly the same.

**Comment by ManWingloeng** [comment]
> I'm having a problem where even if I copy my detection results directly from the ground truth (adding a confidence score of 1.0), certain bounding boxes give an AP of 0 and bring down the mAP unnecessarily.
> 
> For example, try adding `1.txt` to `detection-results` containing:
> `dog 1.0 206 394 173 405`
> and `1.txt` to `ground-truth` containing:
> `dog 206 394 173 405`
> 
> You'll see that it'll return a mAP of zero, despite the bboxes being exactly the same.

I met the same problem.Did u solve it ?

**Comment by micah5** [comment]
Nope, I ended up switching to the official cocoapi to calculate mAP

**Comment by ManWingloeng** [comment]
I find my mistake.I have wrong with generating the txt and making the top greater than bottom.
``` <left> <top> <right> <bottom>```
I forgot to check the bottom>=top,right>=left.
By the way, where is the official cocoapi to calculate mAP?
Thanks.

**Comment by micah5** [comment]
Ah, I see. Thanks.
[Here's](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI) the official cocoapi (python)

**Comment by jiteshm17** [comment]
I have the groundtruths and detections  in the form of `x_min,y_min,x_max,y_max`. Can I use the order `x_min,y_max,x_max,y_min` to match the corresponding order of `<left> <top> <right> <bottom>` mentioned in the txt file or should I change it something else?

**Comment by jiteshm17** [comment]
I have the groundtruths and detections  in the form of `x_min,y_min,x_max,y_max`. Can I use the order `x_min,y_max,x_max,y_min` to match the corresponding order of `<left> <top> <right> <bottom>` mentioned in the txt file or should I change it something else?
