### ISSUE TITLE
Error when labels have "space"

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#9]
Hello @Cartucho i got error (again)

![image](https://user-images.githubusercontent.com/37479922/38689523-16dcb54c-3ea6-11e8-9266-235cfa655b9b.png)

i think this error occur because i have labels which has spacing between the words. 
Can you help me with this ?

Thank you

**Comment by Cartucho** [comment]
yes, that's causing the error.
Today I have no time, but tomorrow I will think about a solution, ok?

**Comment by andikira** [comment]
ok sir i'll wait for that 
thank you so much

**Comment by Cartucho** [comment]
Hi @andikira ! Could you please try the updated code?

**Comment by andikira** [comment]
i got error
![image](https://user-images.githubusercontent.com/37479922/38751610-cd5a1684-3f82-11e8-8481-2a26f9df1e61.png)

**Comment by Cartucho** [comment]
oh right, you use Python 3.
Fixing it...

**Comment by Cartucho** [comment]
It should work now!

**Comment by andikira** [comment]
Great, The extra feature is work now, 
Thank you, but in result folder there is no recall-precision curve, prediction/ground truth diagram etc as usual 

do you know why ?

**Comment by Cartucho** [comment]
do you have the matplotlib installed?

**Comment by andikira** [comment]
haha sorry i forgot that 
Thank you @Cartucho 
closed now

**Comment by Cartucho** [comment]
Btw you gave me an idea! I will write in the code's output:
`matplotlib is currently not installed, please install it to get the resulting plots`

**Comment by Cartucho** [comment]
Done!
![screenshot from 2018-04-14 13-50-13](https://user-images.githubusercontent.com/15831541/38768377-cb5d20fc-3fea-11e8-8b6b-033094f66e06.png)
