### ISSUE TITLE
Score here is different from same metric in COCO tool

### ISSUE THREAD

**Issue by tiberium24** [Cartucho/mAP#96]
Hi,

I am using this repo to find the mAP (50% IOU) and I get for my dataset an mAP of 56.7%. By using this one though https://github.com/cocodataset/cocoapi, I am getting for the same IOU a score of 37.4%. How do you explain the difference?

**Comment by nicolaschianella** [comment]
Hi @tiberium24, have you found out why ?
Best regards

**Comment by Pavan-Samtani** [comment]
Same issue here! mAP according to this repo is lower than https://github.com/cocodataset/cocoapi/tree/master/PythonAPI/pycocotools
